### ISSUE TITLE
autoaudiosrc not found

### ISSUE THREAD

**Issue by Shura0** [ajbogh/blather#16]
Hi.

I have startup error:

```
 ./Blather.py
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
# commands are key:value pairs 

# key is the sentence to listen for

# value is the command to run when the key is spoken

hello world:echo "hello world"

hello world echo "hello world"
Traceback (most recent call last):
  File "./Blather.py", line 286, in <module>
    blather = Blather(options)
  File "./Blather.py", line 49, in __init__
    self.recognizer = Recognizer(lang_file, dic_file, opts.microphone )
  File "/home/shura/projects/blather/Recognizer.py", line 29, in __init__
    self.pipeline=gst.parse_launch( cmd )
glib.GError: no element "autoaudiosrc"
```

libgstpocketsphinx.so is instlled.

```
$ ls /usr/lib64/gstreamer-0.10
gst-plugin-scanner*     libgstaudiorate.so*      libgstdecodebin.so*         libgstgio.so*           libgstpulse.so*     libgsttypefindfunctions.so*  libgstvorbis.so*
libgstadder.so*         libgstaudioresample.so*  libgstdecodebin2.so*        libgstogg.so*           libgstpython.so*    libgstvideorate.so*          libgstximagesink.so*
libgstalsa.so*          libgstaudiotestsrc.so*   libgstencodebin.so*         libgstpango.so*         libgstsubparse.so*  libgstvideoscale.so*         libgstxvimagesink.so*
libgstapp.so*           libgstcoreelements.so*   libgstffmpegcolorspace.so*  libgstplaybin.so*       libgsttcp.so*       libgstvideotestsrc.so*
libgstaudioconvert.so*  libgstcoreindexers.so*   libgstgdp.so*               libgstpocketsphinx.so*  libgsttheora.so*    libgstvolume.so*
```

How to fix it?

**Comment by ajbogh** [comment]
Not sure how to fix this. Others are saying to install all of the [gst plugins](http://stackoverflow.com/questions/35931585/installing-pocketsphinx-with-gstreamer-and-python-in-a-virtualenv). Are you in a virtual machine? 

I will keep this open until I get some time to look into it. Please keep us updated if you eventually find a solution.

**Comment by Shura0** [comment]
All plugins are installed.

It is not virtual machine, it's real. Rosa Linux.
